version: "3.7"

services:
  php-fpm:
    image: docker.pkg.github.com/shipstream/middleware/php:latest
    build: ./docker
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - .:/var/www/html

  nginx:
    image: library/nginx:latest
    ports:
      - "${HOST_PORT:-80}:80"
    links:
      - php-fpm
    volumes:
      - ./docker/nginx.conf:/etc/nginx/templates/default.conf.template:ro
      - .:/var/www/html

  cli:
    image: docker.pkg.github.com/shipstream/middleware/php:latest
    build: ./docker
    working_dir: /var/www/html
    user: www-data
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - .:/var/www/html
    command:
      /bin/true

  cron:
    image: docker.pkg.github.com/shipstream/middleware/php:latest
    build: ./docker
    working_dir: /var/www/html
    user: root
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - .:/var/www/html
    command:
      /bin/true
